// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlNrRmk92kRGBU0TWhV3msR4U6yO3tS_A',
    appId: '1:212909642288:web:d0b94d50754816ed6653f5',
    messagingSenderId: '212909642288',
    projectId: 'nexushub-fe7ba',
    authDomain: 'nexushub-fe7ba.firebaseapp.com',
    storageBucket: 'nexushub-fe7ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlcdslhIn3Z7qgGN9HjE__EyySzqpPU0',
    appId: '1:212909642288:android:35f28f2b974adfcb6653f5',
    messagingSenderId: '212909642288',
    projectId: 'nexushub-fe7ba',
    storageBucket: 'nexushub-fe7ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZaT4wIVlD0nW9bbRKzSlcQb37CFq_5o',
    appId: '1:212909642288:ios:f86e3753c01559396653f5',
    messagingSenderId: '212909642288',
    projectId: 'nexushub-fe7ba',
    storageBucket: 'nexushub-fe7ba.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZaT4wIVlD0nW9bbRKzSlcQb37CFq_5o',
    appId: '1:212909642288:ios:7fc1ed369f0dc8526653f5',
    messagingSenderId: '212909642288',
    projectId: 'nexushub-fe7ba',
    storageBucket: 'nexushub-fe7ba.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
